[book]
authors = ["PIPET 임동석, 한승훈, 한성필, 최수인"]
language = "ko"
src = "src"
title = "청람바이오아카데미 총서 1: 신약개발을 위한 실전 약동학 I"

[output.html]
git-repository-url = "https://github.com/pipetcpt/pharmapk"
edit-url-template = "https://github.com/pipetcpt/pharmapk/edit/master/{path}"

[preprocessor.katex]
renderers = ["html"]
optional = true
